# Generated by Django 2.0.9 on 2018-12-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To', models.CharField(max_length=200)),
                ('From', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('Items', models.TextField()),
                ('Element_no', models.IntegerField()),
                ('Purpose', models.TextField()),
            ],
        ),
    ]
