# Generated by Django 2.0.9 on 2018-12-18 14:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logistic',
            name='Element_no',
        ),
        migrations.RemoveField(
            model_name='logistic',
            name='Items',
        ),
        migrations.RemoveField(
            model_name='logistic',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='logistic',
            name='Item',
            field=models.CharField(choices=[('chair', 'Chair'), ('table', 'Table')], default='chair', max_length=20),
        ),
        migrations.AddField(
            model_name='logistic',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 18, 14, 1, 13, 441119, tzinfo=utc)),
        ),
    ]
