# Generated by Django 2.0.9 on 2018-12-18 14:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_auto_20181218_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistic',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 18, 14, 2, 58, 249103, tzinfo=utc)),
        ),
    ]
