# Generated by Django 2.0.9 on 2018-12-18 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_auto_20181218_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistic',
            name='Timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
